package com.backend.model;

import jakarta.persistence.*;
import lombok.Data;
import java.time.YearMonth;

@Entity
@Data
@Table(name = "monthly_budget")
public class MonthlyBudget {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "year_month_date", nullable = false, unique = true)
    private String yearMonth;

    @Column(nullable = false)
    private Double amount;

    @Column(name = "is_auto_generated")
    private boolean autoGenerated = false;

    // Convert YearMonth to String format
    public void setYearMonth(YearMonth yearMonth) {
        this.yearMonth = yearMonth.toString();
    }

    // Convert String to YearMonth
    public YearMonth getYearMonth() {
        return YearMonth.parse(this.yearMonth);
    }
} 